# Generated by Django 3.1.2 on 2020-11-14 08:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('userID', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('userPhone', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('userEmail', models.EmailField(max_length=254, unique=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('is_admin', models.BooleanField(blank=True, default=False)),
                ('is_staff', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('productName', models.CharField(max_length=255)),
                ('productPrice', models.DecimalField(decimal_places=0, max_digits=10)),
                ('productCategory', models.CharField(choices=[('Wearable', 'Wearable'), ('Electronics', 'Electronics'), ('Books', 'Books'), ('Footwear', 'Footwear'), ('Stationary', 'Stationary')], max_length=32)),
                ('productImage', models.ImageField(upload_to='images/')),
                ('productDescription', models.CharField(max_length=512, null=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('productID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.products')),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulletin1', models.CharField(blank=True, max_length=64, null=True)),
                ('bulletin2', models.CharField(blank=True, max_length=64, null=True)),
                ('bulletin3', models.CharField(blank=True, max_length=64, null=True)),
                ('bulletin4', models.CharField(blank=True, max_length=64, null=True)),
                ('bulletin5', models.CharField(blank=True, max_length=64, null=True)),
                ('productID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.products')),
            ],
            options={
                'verbose_name_plural': 'Attributes',
            },
        ),
    ]
