# Generated by Django 3.1.2 on 2020-11-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201114_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
