# Generated by Django 3.1.2 on 2020-11-15 09:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ratings_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='subject',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='updated_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.products'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='ratings',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
