# Generated by Django 3.1.2 on 2020-11-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201115_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
