# Generated by Django 3.1.2 on 2020-11-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201116_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
