# Generated by Django 3.1.2 on 2020-11-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20201116_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='productImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
