# Generated by Django 3.1.2 on 2020-11-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_orders_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='savedProductPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
